/*
 * Downloads the webfonts into public/fonts and regenerates src/styles/fonts.css.
 *
 * Run after changing weights or adding a locale:  node scripts/fonts.mjs
 * Adding Russian means adding 'cyrillic' and 'cyrillic-ext' to SUBSETS.
 */
import { writeFileSync } from 'node:fs';

const CSS_URL =
  'https://fonts.googleapis.com/css2?family=Archivo:wght@300;400;500&family=Italianno&display=swap';
const UA =
  'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0 Safari/537.36';

// Google's css2 response labels subsets only by unicode-range, so match on the first range.
const SUBSETS = {
  latin: 'U+0000-00FF',
  'latin-ext': 'U+0100-02BA',
};

const css = await (await fetch(CSS_URL, { headers: { 'User-Agent': UA } })).text();

// Archivo is served as one variable file per subset, the same bytes for every
// weight, so faces are keyed by file URL and carry a weight range.
const byUrl = new Map();
for (const block of css.split('@font-face').slice(1)) {
  const family = /font-family: '([^']+)'/.exec(block)[1];
  const weight = Number(/font-weight: (\d+)/.exec(block)[1]);
  const url = /src: url\((https:[^)]+)\)/.exec(block)[1];
  const range = /unicode-range: ([^;]+);/.exec(block)[1].trim();

  const subset = Object.keys(SUBSETS).find((s) => range.startsWith(SUBSETS[s]));
  if (!subset) continue;

  const face = byUrl.get(url);
  if (face) {
    face.min = Math.min(face.min, weight);
    face.max = Math.max(face.max, weight);
  } else {
    byUrl.set(url, {
      family,
      subset,
      range,
      url,
      min: weight,
      max: weight,
      file: `${family.toLowerCase()}-${subset}.woff2`,
    });
  }
}

const faces = [...byUrl.values()];
for (const face of faces) {
  const res = await fetch(face.url);
  if (!res.ok) throw new Error(`${face.file}: HTTP ${res.status}`);
  writeFileSync(`public/fonts/${face.file}`, Buffer.from(await res.arrayBuffer()));
}

const rules = faces
  .map(
    (f) => `@font-face {
  font-family: '${f.family}';
  font-style: normal;
  font-weight: ${f.min === f.max ? f.min : `${f.min} ${f.max}`};
  font-display: swap;
  src: url('/fonts/${f.file}') format('woff2');
  unicode-range: ${f.range};
}`,
  )
  .join('\n\n');

writeFileSync(
  'src/styles/fonts.css',
  `/*
 * Generated by scripts/fonts.mjs — do not edit by hand.
 *
 * Self-hosted, latin + latin-ext only. Not the Google Fonts CDN: that is a
 * third-party connection on the critical path of a homepage that must paint
 * in under a second, and a US transfer that would have to be named in the
 * RODO notice. Archivo is one variable file per subset, so 300-500 costs the
 * same bytes as any single weight.
 */

${rules}\n`,
);

console.log(`${faces.length} files written`);
